=head1 Susan Lunn

=head2 Contact Information

=over

=item
L<susan@lunn.io>

=item
L<http:github.com/snoozan/>

=back

=head2 Objective

Seeking full time employment starting January 2017.

=head2 Technical Skills

=over

=item Languages

=over

=item

Python, Bash, C, Haskell, Java, Javascript, R, Go

=back

=item Operating Systems

=over

=item

Linux, OmniOS/Illumos, FreeBSD, Solaris

=back

=item Tools and Services

=over

=item

AWS, Chef, Terraform, Solr, Icinga, Git, Make, Ansible, Puppet, Docker, RKT, Jenkins, Zabbix, TravisCI,
Solr

=back

=back

=head2 Personal Projects

=head3 Zabbix for Computer Science House

=over

=item 

March 2016

=item

Set up the Zabbix monitoring software for Computer Science House services 
and machine, with full LDAP integration and our own star SSL cert.

=back

=head3 Aphrodite

=over

=item 

February 2015

=item

A Haskell web app using the Scotty framework and Yesod's Template Haskell that
finds all the local Planned Parenthoods within an address/GPS location via the
Google API, and routes the user there via public transportation. It is aimed at
low-income women without access to personal transportation.

=back

=head3 Deploying Docker

=over

=item

November 2014

=item

Deployed a linux container platform that allows the automation of software applications on a local Computer
Science House machine known as Hactar. Docker builds on top of a few different linux container technologies,
and we used it as a test platform for in-house written applications

=back

=head3 MyShell

=over

=item

December 2014

=item

Wrote a basic unix shell in C that implements piping, standard I/O redirection and all commands found
within the PATH variable as well as a set of its own internal commands.

=back

=head2 Experience

=head3 Slack 

=over

=item 

Operations Engineer Intern

=item

September 2016 - Present

=item 

L<https://slack.com/>

=back

Worked on setting up Icinga 2 webUI and high availability distributed monitoring. Helped
rearchitect Solr to allow for better search within Slack. Terraformed the QA enviroment
for both multi and main environments.

=head3 Apple 

=over

=item 

Software Engineer Intern

=item

May 2016 - September 2016 

=item 

L<https://apple.com/>

=back

Worked on adding a collection based restore to SolrCloud, a distributed system and manager
of Solr.

=head3 Rochester Institute of Technology Student Government Services

=over

=item 

Junior Quality Engineer

=item

January 2016 - May 2016

=item 

L<http://sg-rit.edu>

=back

Build tools and processes for continuous integration within the Services team
for Student Government. Using TravisCI and adding rules for Github pushes and
commits.

=head3 Delphix 

=over

=item 

Operations Engineer Intern

=item

August 2015 - January 2016 

=item 

L<https://delphix.com>

=back

Using Jenkins and a series of shell scripts, worked on automating the process for 
standing up a build server. This involved intimate knowledge of OmniOS packaging (IPS)
as well as delving in to the internals of the Delphix stack.

=head3 LinkedIn

=over

=item 

Systems Engineer Intern

=item

06/08/2015 - Present

=item 

L<https://linkedin.com>

=back

Worked to make logs from CF Engine humanly readible. Built thousands of servers
and helped the process which enabaled them to be built more effectively. Helped
Linkedin finalize which container solution to continue with.

=head3 Golisano College of Computing and Informational Sciences

=over

=item

Computer Science Researcher

=item

01/29/2015 - 05/15/2015

=item

L<https://www.cs.rit.edu/research/overview>

=back

Developed a micro-benchmarker that produced statistics and graphs for provided
executables and their corresponding arguments. Written with a python script with
output piped into a graph generated R script, it produced box-and-whisker plots
as well as outputting ANOVA and T-tests for the supplied executables.

=head3 MAGIC Center @ RIT

=over

=item 

Back-end web developer - R+D

=item 

08/15/2014 - 01/15/2015 

=item

L<http://magic.rit.edu/foss/>

=back

Working on writing a web application that uses ArchivesSpace - a standard for
museum websites, to display data about toy makers. It is meant to be displayed 
in a children’s museum soon.

=head3 Earth Moves

=over

=item 

Web developer 

=item 

04/15/2014 - 08/15/2014

=back 

Worked on several applications per client request. My two main projects were building a web scraper
to pull thousands of eye glass frames and aggregate them, from several websites, this was written using the
Python library Scrapy and bootstrap CSS to display data. Then I built a web
application for doctors and hospitals to manage their operation trays, which was written in 
Python using the Pyramid Pylons framework
and bootstrap CSS framework.

=head2 Extracurricular

=over

=item

CSH - Computer Science House

=over

=item

Full active member

=item

L<http://www.csh.rit.edu/>

=back

=item

FOSS@MAGIC(Free Open Source Software) - Active member

=over

=item

Collaborate to make free, open source software and to hack cool things.

=item

L<http://magic.rit.edu/foss/>

=back

=item

US FIRST Robotics Team 1230

=over

=item

Programmer

=item

L<http://www.usfirst.org/>

=back

=back

=for comment
vim:tw=80
