=head1 Susan Lunn

=head2 Contact Information

=over

=item
1535 South Ave

=item
Rochester, NY 14620

=item
L<slunn@csh.rit.edu>

=item
L<http:github.com/emollient/>

=back

=head2 Objective
I am looking for a double-block co-op starting May 2015 until Decemeber of 2015.

=head2 Education

=over

=item Rochester Institute of Technology - Rochester, NY

=item 

Major: B.S. Computer Science

=item 

Expected graduation: May 2018

=back

=head2 Experience

=head3 MAGIC Center @ RIT

=over

=item 

Back-end web developer - R+D

=item 

08/15/2014 - Current

=item

L<http://magic.rit.edu/foss/>

=back

Working on writing a web application that uses ArchivesSpace - a standard for
museum websites, to display data about toy makers. It is meant to be displayed 
in a children’s museum soon.

=head3 Earth Moves

=over

=item 

Web developer 

=item 

04/15/2014 - 08/15/2014

=back 

Worked on several applications per client request. My two main projects were building a web scraper
to pull thousands of eye glass frames and aggregate them, from several websites, this was written using the
Python library Scrapy and bootstrap CSS to display data. Then I built a web application for doctor’s and
hospitals to manage their operation trays, which was written in Python using the Pyramid Pylons framework
and bootstrap CSS framework.

=head2 Technical Skills

=over

=item Fluent Languages

=over

=item

Python, C, BASH, Java

=back

=item Exposed Languages

=over

=item

Julia, Haskell, Go, Javascript

=back

=item Operating Systems

=over

=item Linux distros

=over

=item

Arch, Fedora(16+)

=back

=item

OSX

=back

=item Tools

=over

=item

Docker, Git, Make, LaTeX, parted

=back

=back

=head2 Extracurricular

=over

=item

CSH - Computer Science House

=over

=item

Full active member

=item

L<http://www.csh.rit.edu/>

=back

=item

FOSS@MAGIC(Free Open Source Software) - Active member

=over

=item

Collaborate to make free, open source software and to hack cool things.

=item

L<http://magic.rit.edu/foss/>

=back

=item

US FIRST Robotics Team 1230

=over

=item

Programmer

=item

L<http://www.usfirst.org/>

=back

=back

=for comment
vim:tw=80
